begin
  pkg_dropper.dropTable('cart_products');
  pkg_dropper.dropTable('cart');
  pkg_dropper.dropTable('product_attribute_value');
  pkg_dropper.dropTable('attribute');
  pkg_dropper.dropTable('products');
  pkg_dropper.dropTable('category');
  pkg_dropper.dropTable('authorities');
  pkg_dropper.dropTable('category');
  pkg_dropper.dropTable('shop_users');
  pkg_dropper.dropSeq('cart_product_seq');
end;
  /